server:
  port: 16201
spring:
  application:
    name: app-admin
  cloud:
    nacos:
      server-addr: some-nacos:8848
      discovery:
        namespace: production
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://some-mysql:3306/db_app_admin?useUnicode=true&characterEncoding=UTF8
    username: root
    password: mysql.mengyuanyun
  redis:
    database: 1
    host: some-redis
    port: 6379
    password: redis.mengyuanyun
    jedis:
      pool:
        max-active: 20


auth:
  serviceId: app-admin
  user:
    token-header: Authorization
  client:
    id: app-sample  #不填则默认读取spring.application.name
    secret: 123456

jwt:
  token-header: Authorization
  expire: 14400
  rsa-secret: xx1WET12^%3^(WE45

